name: HMP
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - absl-py=2.1.0
  - aom=3.9.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - contourpy=1.1.1
  - cuda-cccl=12.8.90
  - cuda-cccl_win-64=12.8.90
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.8.90
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - cycler=0.12.1
  - dav1d=1.2.1
  - easydict=1.13
  - einops=0.8.0
  - ffmpeg=7.1.1
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.53.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - glib=2.82.2
  - glib-tools=2.82.2
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h2=4.1.0
  - harfbuzz=10.4.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - intel-openmp=2025.0.4
  - jinja2=3.1.4
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.7
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.9.90
  - libcurand-dev=10.3.9.90
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.23
  - libexpat=2.7.0
  - libffi=3.4.6
  - libglib=2.82.2
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libopus=1.5.2
  - libpng=1.6.47
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.58.4
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libusb=1.0.29
  - libuv=1.50.0
  - libvorbis=1.3.7
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.16
  - libxml2=2.13.6
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - networkx=3.1
  - numpy=1.24.4
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openssl=3.4.1
  - packaging=24.2
  - pango=1.56.3
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.3.1
  - pixman=0.46.4
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.8.2
  - protobuf=4.25.3
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pycparser=2.22
  - pyparsing=3.1.4
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python_abi=3.8
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - qt-main=5.15.15
  - re2=2023.09.01
  - requests=2.32.3
  - scipy=1.10.1
  - sdl2=2.32.54
  - sdl3=3.2.16
  - setuptools=75.3.0
  - sip=6.7.12
  - six=1.16.0
  - svt-av1=3.0.1
  - sympy=1.13.3
  - tbb=2021.13.0
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - werkzeug=3.0.6
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zstandard=0.19.0
  - zstd=1.5.7
